FROM python:3.11.4-slim

ARG MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI

ARG DEFAULT_ARTIFACT_ROOT=$DEFAULT_ARTIFACT_ROOT

ENV MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI} 
ENV DEFAULT_ARTIFACT_ROOT=${DEFAULT_ARTIFACT_ROOT} 

RUN pip install mlflow==2.14.1 psycopg2-binary

EXPOSE 5001


CMD ["sh", "-c", "mlflow server --default-artifact-root ${DEFAULT_ARTIFACT_ROOT}  --backend-store-uri ${MLFLOW_TRACKING_URI} --host '0.0.0.0' --port 5001 --serve-artifacts"]

