FROM python:3.11.4-slim

ARG MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI

RUN pip install mlflow==2.14.1 psycopg2-binary

EXPOSE 5001


CMD ["sh", "-c", "mlflow server --backend-store-uri '${MLFLOW_TRACKING_URI}' --host '0.0.0.0' --port 5001"]

