FROM python:3.11.4-slim

RUN pip install mlflow==2.14.1

EXPOSE 5001


CMD [ \
    "mlflow", "server", \
    "--backend-store-uri", "sqlite:///db/mlflow.db", \
    "--default-artifact-root","./data/artifacts", \
    "--host", "0.0.0.0", \
    "--port", "5001" \
]