# Use the official lightweight Python image.
FROM python:3.11.4-slim

# Set the working directory in the container.
WORKDIR /app

# Copy the current directory contents into the container at /app.
COPY . /app

# Install the required packages.
RUN pip install --no-cache-dir gradio requests

# Expose port 7860 for the Gradio app.
EXPOSE 7860

ENV GRADIO_SERVER_NAME="0.0.0.0"

# Run gradio_app.py when the container launches.
CMD ["python", "gradio_app.py"]
